/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Clases.Proveedores;
import Controller.ctlProveedores;
import javax.swing.JOptionPane;

/**
 *
 * @author jotarlo
 */
public class frmProveedores extends javax.swing.JFrame {

    ctlProveedores  ctlProveedores = new ctlProveedores();
    /**
     * Creates new form frmProduct
     */
    public frmProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtRepresentante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSitioWeb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCllCra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBarrio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Administración de Proveedores");

        jLabel2.setText("Nit");

        jLabel3.setText("Razón Social");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Correo Electrónico");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Representante");

        jLabel7.setText("Sitio Web");

        jLabel8.setText("Dirección");

        jLabel9.setText("Cll/Cra");

        jLabel10.setText("Número");

        jLabel11.setText("Barrio");

        jLabel12.setText("Ciudad");

        jButton1.setText("Volver al Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBarrio, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(txtCllCra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(146, 157, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumero))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRepresentante)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCorreo))
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(219, 219, 219)
                        .addComponent(txtCiudad)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCllCra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      private void cleanForm(){        
     this.txtNit.setText("");
     this.txtRazonSocial.setText("");
     this.txtTelefono.setText("");
     this.txtCorreo.setText("");
     this.txtRepresentante.setText("");
     this.txtSitioWeb.setText("");
     this.txtCllCra.setText("");
     this.txtNumero.setText("");
     this.txtBarrio.setText("");
     this.txtCiudad.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmMenu menu = new frmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nit = this.txtNit.getText();
        String razonZocial = this.txtRazonSocial.getText();
        String telefono = this.txtTelefono.getText();
        String correoelectronico = this.txtCorreo.getText();
        String representante = this.txtRepresentante.getText();
        String sitioWeb = this.txtSitioWeb.getText();
        String calle_Carrera = this.txtCllCra.getText();
        String numero = this.txtNumero.getText();
        String barrio = this.txtBarrio.getText();
        String ciudad = this.txtCiudad.getText();
        
        if(!nit.trim().matches("[0-9]{1,}")){
            JOptionPane.showMessageDialog(this, "Digite el nit de su empresa", "Administrador de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(razonZocial.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite la Razon Social  de su empresa", "Administrador de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
        if(!telefono.trim().matches("[0-9]{1,}")){
            JOptionPane.showMessageDialog(this, "Digite el telefono de su empresa", "Administrador de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(correoelectronico.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite el correo electronico de su empresa", "Administrador de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(representante.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite el nombre del representante  de su empresa", "Administrador de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(sitioWeb.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite la url de su pagina web  correspondiente a  su empresa", "Administrador de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(calle_Carrera.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite la calle o la carrera de su empresa", "Administrador de Direcciones", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(numero.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite el numero asociado a la calle o carrera de la direccion de su empresa", "Administrador de Direcciones", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(barrio.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite el barrio en el que se ubica su empresa", "Administrador de Direcciones", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(ciudad.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite la ciudad donde se ubica su empresa", "Administrador de Direcciones", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
       Proveedores proveedor = new Proveedores();
       
       proveedor.setNit(nit);
       proveedor.setRazonSocial(razonZocial);
       proveedor.setTelefono(telefono);
       proveedor.setCorreoElectronico(correoelectronico);
       proveedor.setRepresentante(representante);
       proveedor.setSitioWeb(sitioWeb);
       proveedor.setCalle_Carrera(calle_Carrera);
       proveedor.setNumero(numero);
       proveedor.setBarrio(barrio);
       proveedor.setCiudad(ciudad);
        
       //comunicacion con el controlador para enviar la base de datos 
        boolean result = ctlProveedores.RegistrarProveedor(proveedor);
        if(result){
            JOptionPane.showMessageDialog(this, "proveedor registrado con exito");
        }else{
            JOptionPane.showMessageDialog(this, "proveedor no pudo ser creado", "Administrador de Proovedores", JOptionPane.ERROR_MESSAGE);

        }
        
                
        this.cleanForm();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String Nit = this.txtNit.getText();
        
        if(!Nit.trim().matches("[0-9]{1,}")){
            JOptionPane.showMessageDialog(this, "digite el nit en numeros", "Administrador de proveedores",JOptionPane.ERROR_MESSAGE);
            return;
        }   
        this.cleanForm();
        Proveedores OProveedor = ctlProveedores.BuscarProveedor(Nit);
        if(OProveedor != null){
            
          this.txtNit.setText(OProveedor.getNit());
          this.txtRazonSocial.setText(OProveedor.getRazonSocial());
          this.txtTelefono.setText(OProveedor.getTelefono());
          this.txtCorreo.setText(OProveedor.getCorreoElectronico());
          this.txtRepresentante.setText(OProveedor.getRepresentante());
          this.txtSitioWeb.setText(OProveedor.getSitioWeb());
          this.txtCllCra.setText(OProveedor.getCalle_Carrera());
          this.txtNumero.setText(OProveedor.getNumero());
          this.txtBarrio.setText(OProveedor.getBarrio());
          this.txtCiudad.setText(OProveedor.getCiudad());
   
        }
        else{
            JOptionPane.showMessageDialog(this, "No esxiste el proveedor con el nit: "  + Nit, " Administrador de proveedores",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String nit = this.txtNit.getText();
        String razonZocial = this.txtRazonSocial.getText();
        String telefono = this.txtTelefono.getText();
        String correoelectronico = this.txtCorreo.getText();
        String representante = this.txtRepresentante.getText();
        String sitioWeb = this.txtSitioWeb.getText();
        String calle_Carrera = this.txtCllCra.getText();
        String numero = this.txtNumero.getText();
        String barrio = this.txtBarrio.getText();
        String ciudad = this.txtCiudad.getText();
        
        if(!nit.trim().matches("[0-9]{1,}")){
            JOptionPane.showMessageDialog(this, "Digite el nit de su empresa", "administracion de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(razonZocial.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite la Razon Social  de su empresa", "administracion de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
        if(!telefono.trim().matches("[0-9]{1,}")){
            JOptionPane.showMessageDialog(this, "Digite el telefono de su empresa", "administracion de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(correoelectronico.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite el correo electronico de su empresa", "administracion de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(representante.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite el nombre del representante  de su empresa", "administracion de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(sitioWeb.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite la url de su pagina web  correspondiente a  su empresa", "administracion de proveedores", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(calle_Carrera.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite la calle o la carrera de su empresa", "administracion de Direcciones", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(numero.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite el numero asociado a la calle o carrera de la direccion de su empresa", "administracion de Direcciones", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(barrio.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite el barrio en el que se ubica su empresa", "administracion de Direcciones", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(ciudad.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite la ciudad donde se ubica su empresa", "administracion de Direcciones", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.cleanForm();
        
       Proveedores proveedor = new Proveedores();
       
       proveedor.setNit(nit);
       proveedor.setRazonSocial(razonZocial);
       proveedor.setTelefono(telefono);
       proveedor.setCorreoElectronico(correoelectronico);
       proveedor.setRepresentante(representante);
       proveedor.setSitioWeb(sitioWeb);
       proveedor.setCalle_Carrera(calle_Carrera);
       proveedor.setNumero(numero);
       proveedor.setBarrio(barrio);
       proveedor.setCiudad(ciudad);

       String resultAct = ctlProveedores.ActualizarProveedor(proveedor);
       
       if(resultAct.equals("")){
            
           JOptionPane.showMessageDialog(this, "Se actualizo con exito ", " Administrador de proveedores",JOptionPane.INFORMATION_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(this, resultAct, " Administrador de proveedores",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         String nit = this.txtNit.getText();
        
        if(!nit.trim().matches("[0-9]{1,}")){
            JOptionPane.showMessageDialog(this, "digite el nit en numeros", "gestion de proveedores",JOptionPane.ERROR_MESSAGE);
            return;
        } 
        
        Proveedores result = ctlProveedores.BuscarProveedor(nit);
        if(result != null){
            boolean resulDelete = ctlProveedores.EliminarProveedor(nit);
            if(resulDelete)
                JOptionPane.showMessageDialog(this, "Se elimino con exito ", " Administrador de proveedores",JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "ocurrio un error al tratar de eliminar el proveedor ", " Administrador de proveedores", JOptionPane.ERROR_MESSAGE);

        }else{
        
            JOptionPane.showMessageDialog(this, "No se encontro ningun Proveedor con ese NIT ", " Administrador de proveedores", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCllCra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextField txtSitioWeb;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
