-- MySQL Script generated by MySQL Workbench
-- Sat Jul  9 16:06:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supermercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supermercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supermercado` DEFAULT CHARACTER SET utf8 ;
USE `supermercado` ;

-- -----------------------------------------------------
-- Table `supermercado`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`telefono` (
  `idtelefono` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idtelefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`direccion` (
  `iddireccion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `calle_carrera` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `barrio` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`proveedor` (
  `idproveedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NIT` VARCHAR(45) NOT NULL,
  `razon_social` VARCHAR(45) NOT NULL,
  `correo_electronico` VARCHAR(80) NOT NULL,
  `representate_legal` VARCHAR(45) NOT NULL,
  `sitio_web` VARCHAR(45) NOT NULL,
  `telefono_idtelefono` INT UNSIGNED NOT NULL,
  `direccion_iddireccion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idproveedor`),
  INDEX `fk_proveedor_telefono1_idx` (`telefono_idtelefono` ASC) VISIBLE,
  INDEX `fk_proveedor_direccion1_idx` (`direccion_iddireccion` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_telefono1`
    FOREIGN KEY (`telefono_idtelefono`)
    REFERENCES `supermercado`.`telefono` (`idtelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_direccion1`
    FOREIGN KEY (`direccion_iddireccion`)
    REFERENCES `supermercado`.`direccion` (`iddireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`credito_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`credito_cliente` (
  `idcredito_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `credito_aprobado` BIT NOT NULL,
  `monto_maximo` FLOAT NULL,
  `interes` FLOAT NULL,
  PRIMARY KEY (`idcredito_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`cliente` (
  `idcliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `documento_identidad` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo_electronico` VARCHAR(80) NOT NULL,
  `telefono_idtelefono` INT UNSIGNED NOT NULL,
  `direccion_iddireccion` INT UNSIGNED NOT NULL,
  `credito_cliente_idcredito_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `documento_identidad_UNIQUE` (`documento_identidad` ASC) VISIBLE,
  INDEX `fk_cliente_telefono_idx` (`telefono_idtelefono` ASC) VISIBLE,
  INDEX `fk_cliente_direccion1_idx` (`direccion_iddireccion` ASC) VISIBLE,
  INDEX `fk_cliente_credito_cliente1_idx` (`credito_cliente_idcredito_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_telefono`
    FOREIGN KEY (`telefono_idtelefono`)
    REFERENCES `supermercado`.`telefono` (`idtelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_direccion1`
    FOREIGN KEY (`direccion_iddireccion`)
    REFERENCES `supermercado`.`direccion` (`iddireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_credito_cliente1`
    FOREIGN KEY (`credito_cliente_idcredito_cliente`)
    REFERENCES `supermercado`.`credito_cliente` (`idcredito_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`categoria` (
  `idcategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`producto` (
  `idproducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `existencia` INT NOT NULL,
  `proveedor_idproveedor` INT UNSIGNED NOT NULL,
  `categoria_idcategoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_proveedor1_idx` (`proveedor_idproveedor` ASC) VISIBLE,
  INDEX `fk_producto_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `supermercado`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `supermercado`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`ventas` (
  `idventas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATE NOT NULL,
  `valor_descuento` FLOAT NOT NULL DEFAULT 0,
  `valor_total` FLOAT NOT NULL,
  `cliente_idcliente` INT UNSIGNED NOT NULL,
  `numero_factura` VARCHAR(45) NULL,
  PRIMARY KEY (`idventas`),
  INDEX `fk_ventas_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `supermercado`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`medios_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`medios_pago` (
  `idmedios_pago` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `t_debito` VARCHAR(45) NULL,
  `efectivo` VARCHAR(45) NULL,
  `t_credito` VARCHAR(45) NULL,
  `credito_cliente_idcredito_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmedios_pago`),
  INDEX `fk_medios_pago_credito_cliente1_idx` (`credito_cliente_idcredito_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_medios_pago_credito_cliente1`
    FOREIGN KEY (`credito_cliente_idcredito_cliente`)
    REFERENCES `supermercado`.`credito_cliente` (`idcredito_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermercado`.`ventas_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`ventas_producto` (
  `ventas_idventas` INT UNSIGNED NOT NULL,
  `producto_idproducto` INT UNSIGNED NOT NULL,
  `medios_pago_idmedios_pago` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ventas_idventas`, `producto_idproducto`),
  INDEX `fk_ventas_has_producto_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_ventas_has_producto_ventas1_idx` (`ventas_idventas` ASC) VISIBLE,
  INDEX `fk_ventas_has_producto_medios_pago1_idx` (`medios_pago_idmedios_pago` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_has_producto_ventas1`
    FOREIGN KEY (`ventas_idventas`)
    REFERENCES `supermercado`.`ventas` (`idventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_has_producto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `supermercado`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_has_producto_medios_pago1`
    FOREIGN KEY (`medios_pago_idmedios_pago`)
    REFERENCES `supermercado`.`medios_pago` (`idmedios_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Insercion de Datos
INSERT INTO direccion (calle_carrera, numero,barrio, ciudad)VALUES (
'CALLE 34',
'53',
'PUERTAS DEL SOL',
'MANIZALES'
),
(
'CALLE 43',
'5',
'ENEA',
'MANIZALES'
),
(
'CALLE 85',
'62',
'PERALONSO',
'MANIZALES'
),
(
'CALLE 32',
'28',
'CENTRO',
'MANIZALES'
),
(
'CARRERA 25',
'28',
'CENTRO',
'MANIZALES'
),
(
'CArrera 34',
'35',
'ALAMEDA',
'MANIZALES'
),
(
'CALLE 18',
'96',
'ENEA',
'MANIZALES'
),
(
'CALLE 10',
'26',
'EL BOSQUE',
'MANIZALES'
),
(
'CALLE 23',
'17',
'CENTRO',
'MANIZALES'
),
(
'CARRERA 12',
'32',
'VILLA CAFE',
'MANIZALES'
);


INSERT INTO telefono (telefono)VALUES (
'11111111'
),
(
'2222222'

),
(
'3333333'

),
(
'4444444'
),
(
'555555'
),
(
'666666'
),
(
'7777777'

),
(
'8888888'

),
(
'9999999'
),
(
'10101010'
);

INSERT INTo categoria (nombre, descripcion) VALUES (
'VERDURAS',
'PRODUCTOS DEL CAMPO'
),
(
'LACTEOS',
'PRODUCTOS DERIVADOS DE LA LECHE'
),
(
'FRUTAS',
'FRUTAS DEL CAMPO'
),
(
'CEREALES',
'AVENAS Y CEREALES EN GENERAL'
),
(
'ASEO',
'PRODUCTOS PARA EL HOGAR Y ASEO PERSONAL'
);

INSERT INTo credito_cliente (credito_aprobado, monto_maximo, interes ) VALUES (
1,
500000,
5
),
(
0,
0,
0
),
(
1,
800000,
2
),
(
0,
0,
0
),
(
1,
90000,
10
);

INSERT INTO cliente (documento_identidad,nombres,apellidos,correo_electronico,telefono_idtelefono,direccion_iddireccion,credito_cliente_idcredito_cliente ) VALUES (
1053864852,
'juan manuel',
'buitrago',
'juan@gmail.com',
1,
1,
1
),
(
1053,
'manuela',
'zuluaga',
'manuela@gmail.com',
2,
2,
2
),
(
164852,
'felipe',
'zalazar',
'felipe@gmail.com',
3,
3,
3
),
(
1053852,
'andrea',
'lopez',
'andrea@gmail.com',
4,
4,
4
),
(
10648562,
'valentina',
'buitrago',
'valentian@gmail.com',
1,
1,
1
);

INSERT INTO proveedor(NIT,razon_social,correo_electronico,representate_legal,sitio_web,telefono_idtelefono,direccion_iddireccion) VALUES (
1111111,
'TIENDA DON PEPE',
'PEPE@GMAIL.COM',
'PEPEMOJICA',
'TIENDADONPEPE.COM',
6,
6
),
(
22222222,
'ABARROTES LUZ MARI',
'MARI@GMAIL.COM',
'LUZ MARINA ',
'ABARROTES.COM',
7,
7
),
(
333333,
'DISTRIBUIDORA MAYORISTA',
'DTRIMAYORISTA@GMAIL.COM',
'ALEJANDRO GARCIA',
'.COM',
8,
8
),
(
4444444,
'TIENDA DEL CENTRO',
'BRUNO@GMAIL.COM',
'BRUNO MARS',
'TIENDAELCENTRO.COM',
9,
9
),
(
55555555,
'TIENDA DON PEPE2',
'PEPE@GMAIL.COM',
'PEPEMOJICA',
'TIENDADONPEPE2.COM',
10,
10
);

INSERT INTO producto(nombre,precio,existencia,proveedor_idproveedor,categoria_idcategoria ) VALUES (
'YUCA',
5000,
80,
1,
1
),
(
'LECHE',
5000,
80,
2,
2
),
(
'MANZANA',
8000,
90,
3,
3
),
(
'AVENA',
2000,
100,
4,
4
),
(
'JABON',
3000,
90,
5,
5
);

INSERT INTO medios_pago(t_credito,credito_cliente_idcredito_cliente) VALUES (
'TARJETA CREDITO',
'1'
);
INSERT INTO medios_pago(efectivo,credito_cliente_idcredito_cliente) VALUES (
'EFECTIVO',
'2'
);
INSERT INTO medios_pago(t_debito,credito_cliente_idcredito_cliente) VALUES (
'TARJETA DEBITO',
'3'
);
INSERT INTO medios_pago(t_debito,credito_cliente_idcredito_cliente) VALUES (
'EFECTIVO',
'4'
);
INSERT INTO medios_pago(t_credito,credito_cliente_idcredito_cliente) VALUES (
'CREDITO supermercado',
'5'
);


INSERT INTO ventas(fecha_venta,valor_total,cliente_idcliente,numero_factura ) VALUES (
'2021-05-25',
50000,
1,
1
),
(
'2022-03-22',
50000,
2,
2
),
(
'2022-05-15',
100000,
3,
3
),
(
'2022-07-25',
60000,
4,
4
),
(
'2021-08-25',
80000,
5,
5
);

INSERT INTO ventas_producto(ventas_idventas,producto_idproducto,medios_pago_idmedios_pago ) VALUES (
1,
1,
1

),
(
2,
2,
2
),
(
3,
3,
3
),
(
4,
4,
4
),
(
5,
5,
5
);

SELECT *
FROM producto;

SELECT razon_social, nombre
FROM proveedor INNER JOIN producto
ON proveedor_idproveedor = idproveedor;

SELECT nombres, valor_total, fecha_venta
FROM cliente INNER JOIN ventas
ON cliente_idcliente = idcliente;

SELECT nombres, valor_total, nombre
FROM cliente INNER JOIN ventas
INNER JOIN ventas_producto
INNER JOIN producto
ON cliente_idcliente = idcliente AND idventas = ventas_idventas AND ventas_idventas =  producto_idproducto;
